DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = root intermediate sink
all: rs

SMALL=1
CONTIKI_WITH_IPV6 = 1
CONTIKI = ../../..

MODULES += core/net/ipv6/multicast

include $(CONTIKI)/Makefile.include
